/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */

export type DistributionControllerGetPendingBatches200BatchesItemDestinationsItem = {
  chainSelector?: number;
  receiver?: string;
  amount?: string;
};
