/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PolkaTap Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { DistributionControllerGetPendingBatches200BatchesItemLpSharesItem } from './distributionControllerGetPendingBatches200BatchesItemLpSharesItem';
import type { DistributionControllerGetPendingBatches200BatchesItemDestinationsItem } from './distributionControllerGetPendingBatches200BatchesItemDestinationsItem';

export type DistributionControllerGetPendingBatches200BatchesItem = {
  epochId?: number;
  totalRewards?: string;
  snapshotBlock?: number;
  lpShares?: DistributionControllerGetPendingBatches200BatchesItemLpSharesItem[];
  destinations?: DistributionControllerGetPendingBatches200BatchesItemDestinationsItem[];
};
