/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { DistributionControllerGetPendingBatches200BatchesItem } from './distributionControllerGetPendingBatches200BatchesItem';

export type DistributionControllerGetPendingBatches200 = {
  batches?: DistributionControllerGetPendingBatches200BatchesItem[];
};
