/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserBetHistoryStatus } from './getUserBetHistoryStatus';
import type { GetUserBetHistoryBetType } from './getUserBetHistoryBetType';

export type GetUserBetHistoryParams = {
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
pageSize?: number;
/**
 * Filter by game ID
 */
gameId?: string;
/**
 * Filter by bet status
 */
status?: GetUserBetHistoryStatus;
/**
 * Filter by bet type
 */
betType?: GetUserBetHistoryBetType;
};
