/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */

export type GetUserBetHistoryBetType = typeof GetUserBetHistoryBetType[keyof typeof GetUserBetHistoryBetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserBetHistoryBetType = {
  WINNER: 'WINNER',
  WEREWOLF: 'WEREWOLF',
  NEXT_DEATH: 'NEXT_DEATH',
} as const;
