/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */

export type OhlcControllerGetOhlcSource = typeof OhlcControllerGetOhlcSource[keyof typeof OhlcControllerGetOhlcSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OhlcControllerGetOhlcSource = {
  internal: 'internal',
  chainlink: 'chainlink',
} as const;
