/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PolkaTap Bot API
 * OpenAPI spec version: 0.0.12
 */

export type OhlcControllerGetOhlc503 = {
  error?: string;
  message?: string;
  retryable?: boolean;
};
