/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PolkaTap Bot API
 * OpenAPI spec version: 0.0.12
 */

export type OrderControllerGetUserOrdersStatus = typeof OrderControllerGetUserOrdersStatus[keyof typeof OrderControllerGetUserOrdersStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderControllerGetUserOrdersStatus = {
  OPEN: 'OPEN',
  SETTLED: 'SETTLED',
  REJECTED: 'REJECTED',
} as const;
