/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PolkaTap Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { Cell } from './cell';

export interface PlaceOrderDto {
  cell: Cell;
  marketId: string;
  amount: string;
}
