/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PolkaTap Bot API
 * OpenAPI spec version: 0.0.12
 */

export interface RunAnchorBatchDto {
  /** Maximum number of settled orders to include in this batch */
  maxOrders?: number;
  /** Optional explicit batch ID for debugging/demo runs */
  batchId?: string;
}
