/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Tapl Bot API
 * OpenAPI spec version: 0.0.12
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuthControllerGetChallengeParams,
  DepositDto,
  DistributionControllerGetPendingBatches200,
  ExpireTimeoutDto,
  FinalizeWithdrawalDto,
  HcsAnchorControllerGetBatchesParams,
  OhlcControllerGetOhlc200,
  OhlcControllerGetOhlc401,
  OhlcControllerGetOhlc503,
  OhlcControllerGetOhlcParams,
  OrderControllerGetUserOrdersParams,
  PlaceOrderDto,
  RunAnchorBatchDto,
  WithdrawRequestDto,
} from "./models";

import { customClient } from "./custom-client";
import type { ErrorType, BodyType } from "./custom-client";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const healthCheckControllerHealthCheck = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/health-check`, method: "GET", signal },
    options,
  );
};

export const getHealthCheckControllerHealthCheckQueryKey = () => {
  return [`/api/health-check`] as const;
};

export const getHealthCheckControllerHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheckControllerHealthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheckControllerHealthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHealthCheckControllerHealthCheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthCheckControllerHealthCheck>>
  > = ({ signal }) => healthCheckControllerHealthCheck(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheckControllerHealthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckControllerHealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheckControllerHealthCheck>>
>;
export type HealthCheckControllerHealthCheckQueryError = ErrorType<unknown>;

export function useHealthCheckControllerHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheckControllerHealthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheckControllerHealthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckControllerHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a challenge message to sign
 */
export const authControllerGetChallenge = (
  params: AuthControllerGetChallengeParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/auth/challenge`, method: "GET", params, signal },
    options,
  );
};

export const getAuthControllerGetChallengeQueryKey = (
  params?: AuthControllerGetChallengeParams,
) => {
  return [`/api/auth/challenge`, ...(params ? [params] : [])] as const;
};

export const getAuthControllerGetChallengeQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetChallenge>>,
  TError = ErrorType<unknown>,
>(
  params: AuthControllerGetChallengeParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof authControllerGetChallenge>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetChallengeQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetChallenge>>
  > = ({ signal }) =>
    authControllerGetChallenge(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetChallenge>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthControllerGetChallengeQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetChallenge>>
>;
export type AuthControllerGetChallengeQueryError = ErrorType<unknown>;

/**
 * @summary Get a challenge message to sign
 */

export function useAuthControllerGetChallenge<
  TData = Awaited<ReturnType<typeof authControllerGetChallenge>>,
  TError = ErrorType<unknown>,
>(
  params: AuthControllerGetChallengeParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof authControllerGetChallenge>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAuthControllerGetChallengeQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Login with signed challenge
 */
export const authControllerLogin = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/auth/login`, method: "POST", signal },
    options,
  );
};

export const getAuthControllerLoginMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogin>>,
    void
  > = () => {
    return authControllerLogin(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>;

export type AuthControllerLoginMutationError = ErrorType<unknown>;

/**
 * @summary Login with signed challenge
 */
export const useAuthControllerLogin = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Get a new WSS key (requires JWT)
 */
export const authControllerGetWssKey = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/auth/wss-key`, method: "GET", signal },
    options,
  );
};

export const getAuthControllerGetWssKeyQueryKey = () => {
  return [`/api/auth/wss-key`] as const;
};

export const getAuthControllerGetWssKeyQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetWssKey>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetWssKey>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetWssKeyQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetWssKey>>
  > = ({ signal }) => authControllerGetWssKey(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetWssKey>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthControllerGetWssKeyQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetWssKey>>
>;
export type AuthControllerGetWssKeyQueryError = ErrorType<unknown>;

/**
 * @summary Get a new WSS key (requires JWT)
 */

export function useAuthControllerGetWssKey<
  TData = Awaited<ReturnType<typeof authControllerGetWssKey>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetWssKey>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAuthControllerGetWssKeyQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const orderControllerPlaceOrder = (
  placeOrderDto: BodyType<PlaceOrderDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    {
      url: `/api/orders`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: placeOrderDto,
      signal,
    },
    options,
  );
};

export const getOrderControllerPlaceOrderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof orderControllerPlaceOrder>>,
    TError,
    { data: BodyType<PlaceOrderDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof orderControllerPlaceOrder>>,
  TError,
  { data: BodyType<PlaceOrderDto> },
  TContext
> => {
  const mutationKey = ["orderControllerPlaceOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof orderControllerPlaceOrder>>,
    { data: BodyType<PlaceOrderDto> }
  > = (props) => {
    const { data } = props ?? {};

    return orderControllerPlaceOrder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrderControllerPlaceOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof orderControllerPlaceOrder>>
>;
export type OrderControllerPlaceOrderMutationBody = BodyType<PlaceOrderDto>;
export type OrderControllerPlaceOrderMutationError = ErrorType<unknown>;

export const useOrderControllerPlaceOrder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof orderControllerPlaceOrder>>,
    TError,
    { data: BodyType<PlaceOrderDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof orderControllerPlaceOrder>>,
  TError,
  { data: BodyType<PlaceOrderDto> },
  TContext
> => {
  const mutationOptions = getOrderControllerPlaceOrderMutationOptions(options);

  return useMutation(mutationOptions);
};

export const orderControllerGetUserOrders = (
  params?: OrderControllerGetUserOrdersParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/orders/user`, method: "GET", params, signal },
    options,
  );
};

export const getOrderControllerGetUserOrdersQueryKey = (
  params?: OrderControllerGetUserOrdersParams,
) => {
  return [`/api/orders/user`, ...(params ? [params] : [])] as const;
};

export const getOrderControllerGetUserOrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof orderControllerGetUserOrders>>,
  TError = ErrorType<unknown>,
>(
  params?: OrderControllerGetUserOrdersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof orderControllerGetUserOrders>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getOrderControllerGetUserOrdersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof orderControllerGetUserOrders>>
  > = ({ signal }) =>
    orderControllerGetUserOrders(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof orderControllerGetUserOrders>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type OrderControllerGetUserOrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof orderControllerGetUserOrders>>
>;
export type OrderControllerGetUserOrdersQueryError = ErrorType<unknown>;

export function useOrderControllerGetUserOrders<
  TData = Awaited<ReturnType<typeof orderControllerGetUserOrders>>,
  TError = ErrorType<unknown>,
>(
  params?: OrderControllerGetUserOrdersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof orderControllerGetUserOrders>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getOrderControllerGetUserOrdersQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const accountControllerGetBalance = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/account/balance`, method: "GET", signal },
    options,
  );
};

export const getAccountControllerGetBalanceQueryKey = () => {
  return [`/api/account/balance`] as const;
};

export const getAccountControllerGetBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof accountControllerGetBalance>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof accountControllerGetBalance>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountControllerGetBalanceQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountControllerGetBalance>>
  > = ({ signal }) => accountControllerGetBalance(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof accountControllerGetBalance>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountControllerGetBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerGetBalance>>
>;
export type AccountControllerGetBalanceQueryError = ErrorType<unknown>;

export function useAccountControllerGetBalance<
  TData = Awaited<ReturnType<typeof accountControllerGetBalance>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof accountControllerGetBalance>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAccountControllerGetBalanceQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const paymentControllerRequestWithdrawal = (
  withdrawRequestDto: BodyType<WithdrawRequestDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    {
      url: `/api/payment/withdraw`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: withdrawRequestDto,
      signal,
    },
    options,
  );
};

export const getPaymentControllerRequestWithdrawalMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerRequestWithdrawal>>,
    TError,
    { data: BodyType<WithdrawRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentControllerRequestWithdrawal>>,
  TError,
  { data: BodyType<WithdrawRequestDto> },
  TContext
> => {
  const mutationKey = ["paymentControllerRequestWithdrawal"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentControllerRequestWithdrawal>>,
    { data: BodyType<WithdrawRequestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return paymentControllerRequestWithdrawal(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerRequestWithdrawalMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerRequestWithdrawal>>
>;
export type PaymentControllerRequestWithdrawalMutationBody =
  BodyType<WithdrawRequestDto>;
export type PaymentControllerRequestWithdrawalMutationError =
  ErrorType<unknown>;

export const usePaymentControllerRequestWithdrawal = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerRequestWithdrawal>>,
    TError,
    { data: BodyType<WithdrawRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof paymentControllerRequestWithdrawal>>,
  TError,
  { data: BodyType<WithdrawRequestDto> },
  TContext
> => {
  const mutationOptions =
    getPaymentControllerRequestWithdrawalMutationOptions(options);

  return useMutation(mutationOptions);
};

export const paymentControllerDebugDeposit = (
  depositDto: BodyType<DepositDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    {
      url: `/api/payment/debug/deposit`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: depositDto,
      signal,
    },
    options,
  );
};

export const getPaymentControllerDebugDepositMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerDebugDeposit>>,
    TError,
    { data: BodyType<DepositDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentControllerDebugDeposit>>,
  TError,
  { data: BodyType<DepositDto> },
  TContext
> => {
  const mutationKey = ["paymentControllerDebugDeposit"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentControllerDebugDeposit>>,
    { data: BodyType<DepositDto> }
  > = (props) => {
    const { data } = props ?? {};

    return paymentControllerDebugDeposit(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerDebugDepositMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerDebugDeposit>>
>;
export type PaymentControllerDebugDepositMutationBody = BodyType<DepositDto>;
export type PaymentControllerDebugDepositMutationError = ErrorType<unknown>;

export const usePaymentControllerDebugDeposit = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerDebugDeposit>>,
    TError,
    { data: BodyType<DepositDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof paymentControllerDebugDeposit>>,
  TError,
  { data: BodyType<DepositDto> },
  TContext
> => {
  const mutationOptions =
    getPaymentControllerDebugDepositMutationOptions(options);

  return useMutation(mutationOptions);
};

export const paymentControllerDebugFinalizeWithdrawal = (
  finalizeWithdrawalDto: BodyType<FinalizeWithdrawalDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    {
      url: `/api/payment/debug/finalize-withdrawal`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: finalizeWithdrawalDto,
      signal,
    },
    options,
  );
};

export const getPaymentControllerDebugFinalizeWithdrawalMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerDebugFinalizeWithdrawal>>,
    TError,
    { data: BodyType<FinalizeWithdrawalDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentControllerDebugFinalizeWithdrawal>>,
  TError,
  { data: BodyType<FinalizeWithdrawalDto> },
  TContext
> => {
  const mutationKey = ["paymentControllerDebugFinalizeWithdrawal"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentControllerDebugFinalizeWithdrawal>>,
    { data: BodyType<FinalizeWithdrawalDto> }
  > = (props) => {
    const { data } = props ?? {};

    return paymentControllerDebugFinalizeWithdrawal(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerDebugFinalizeWithdrawalMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof paymentControllerDebugFinalizeWithdrawal>>
  >;
export type PaymentControllerDebugFinalizeWithdrawalMutationBody =
  BodyType<FinalizeWithdrawalDto>;
export type PaymentControllerDebugFinalizeWithdrawalMutationError =
  ErrorType<unknown>;

export const usePaymentControllerDebugFinalizeWithdrawal = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerDebugFinalizeWithdrawal>>,
    TError,
    { data: BodyType<FinalizeWithdrawalDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof paymentControllerDebugFinalizeWithdrawal>>,
  TError,
  { data: BodyType<FinalizeWithdrawalDto> },
  TContext
> => {
  const mutationOptions =
    getPaymentControllerDebugFinalizeWithdrawalMutationOptions(options);

  return useMutation(mutationOptions);
};

export const paymentControllerDebugExpireTimeout = (
  expireTimeoutDto: BodyType<ExpireTimeoutDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    {
      url: `/api/payment/debug/expire-timeout`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: expireTimeoutDto,
      signal,
    },
    options,
  );
};

export const getPaymentControllerDebugExpireTimeoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerDebugExpireTimeout>>,
    TError,
    { data: BodyType<ExpireTimeoutDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentControllerDebugExpireTimeout>>,
  TError,
  { data: BodyType<ExpireTimeoutDto> },
  TContext
> => {
  const mutationKey = ["paymentControllerDebugExpireTimeout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentControllerDebugExpireTimeout>>,
    { data: BodyType<ExpireTimeoutDto> }
  > = (props) => {
    const { data } = props ?? {};

    return paymentControllerDebugExpireTimeout(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerDebugExpireTimeoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerDebugExpireTimeout>>
>;
export type PaymentControllerDebugExpireTimeoutMutationBody =
  BodyType<ExpireTimeoutDto>;
export type PaymentControllerDebugExpireTimeoutMutationError =
  ErrorType<unknown>;

export const usePaymentControllerDebugExpireTimeout = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerDebugExpireTimeout>>,
    TError,
    { data: BodyType<ExpireTimeoutDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof paymentControllerDebugExpireTimeout>>,
  TError,
  { data: BodyType<ExpireTimeoutDto> },
  TContext
> => {
  const mutationOptions =
    getPaymentControllerDebugExpireTimeoutMutationOptions(options);

  return useMutation(mutationOptions);
};

export const paymentControllerGetUserDeposits = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/payment/deposits`, method: "GET", signal },
    options,
  );
};

export const getPaymentControllerGetUserDepositsQueryKey = () => {
  return [`/api/payment/deposits`] as const;
};

export const getPaymentControllerGetUserDepositsQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentControllerGetUserDeposits>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetUserDeposits>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPaymentControllerGetUserDepositsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof paymentControllerGetUserDeposits>>
  > = ({ signal }) => paymentControllerGetUserDeposits(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetUserDeposits>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PaymentControllerGetUserDepositsQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerGetUserDeposits>>
>;
export type PaymentControllerGetUserDepositsQueryError = ErrorType<unknown>;

export function usePaymentControllerGetUserDeposits<
  TData = Awaited<ReturnType<typeof paymentControllerGetUserDeposits>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetUserDeposits>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPaymentControllerGetUserDepositsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const paymentControllerGetActiveWithdrawalSession = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/payment/withdrawal/session`, method: "GET", signal },
    options,
  );
};

export const getPaymentControllerGetActiveWithdrawalSessionQueryKey = () => {
  return [`/api/payment/withdrawal/session`] as const;
};

export const getPaymentControllerGetActiveWithdrawalSessionQueryOptions = <
  TData = Awaited<
    ReturnType<typeof paymentControllerGetActiveWithdrawalSession>
  >,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetActiveWithdrawalSession>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPaymentControllerGetActiveWithdrawalSessionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof paymentControllerGetActiveWithdrawalSession>>
  > = ({ signal }) =>
    paymentControllerGetActiveWithdrawalSession(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetActiveWithdrawalSession>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PaymentControllerGetActiveWithdrawalSessionQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof paymentControllerGetActiveWithdrawalSession>>
  >;
export type PaymentControllerGetActiveWithdrawalSessionQueryError =
  ErrorType<unknown>;

export function usePaymentControllerGetActiveWithdrawalSession<
  TData = Awaited<
    ReturnType<typeof paymentControllerGetActiveWithdrawalSession>
  >,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetActiveWithdrawalSession>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getPaymentControllerGetActiveWithdrawalSessionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const paymentControllerGetUserWithdrawals = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/payment/withdrawals`, method: "GET", signal },
    options,
  );
};

export const getPaymentControllerGetUserWithdrawalsQueryKey = () => {
  return [`/api/payment/withdrawals`] as const;
};

export const getPaymentControllerGetUserWithdrawalsQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentControllerGetUserWithdrawals>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetUserWithdrawals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPaymentControllerGetUserWithdrawalsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof paymentControllerGetUserWithdrawals>>
  > = ({ signal }) =>
    paymentControllerGetUserWithdrawals(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetUserWithdrawals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PaymentControllerGetUserWithdrawalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerGetUserWithdrawals>>
>;
export type PaymentControllerGetUserWithdrawalsQueryError = ErrorType<unknown>;

export function usePaymentControllerGetUserWithdrawals<
  TData = Awaited<ReturnType<typeof paymentControllerGetUserWithdrawals>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof paymentControllerGetUserWithdrawals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getPaymentControllerGetUserWithdrawalsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns 1-second OHLC candles for price integrity verification. Supports both real-time (last 30 minutes from cache) and historical mock data. Header: Authorization: Bearer {APP_API_KEY}
 * @summary Get OHLC candles for a time window
 */
export const ohlcControllerGetOhlc = (
  params: OhlcControllerGetOhlcParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<OhlcControllerGetOhlc200>(
    { url: `/api/v1/ohlc`, method: "GET", params, signal },
    options,
  );
};

export const getOhlcControllerGetOhlcQueryKey = (
  params?: OhlcControllerGetOhlcParams,
) => {
  return [`/api/v1/ohlc`, ...(params ? [params] : [])] as const;
};

export const getOhlcControllerGetOhlcQueryOptions = <
  TData = Awaited<ReturnType<typeof ohlcControllerGetOhlc>>,
  TError = ErrorType<OhlcControllerGetOhlc401 | OhlcControllerGetOhlc503>,
>(
  params: OhlcControllerGetOhlcParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof ohlcControllerGetOhlc>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getOhlcControllerGetOhlcQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof ohlcControllerGetOhlc>>
  > = ({ signal }) => ohlcControllerGetOhlc(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof ohlcControllerGetOhlc>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type OhlcControllerGetOhlcQueryResult = NonNullable<
  Awaited<ReturnType<typeof ohlcControllerGetOhlc>>
>;
export type OhlcControllerGetOhlcQueryError = ErrorType<
  OhlcControllerGetOhlc401 | OhlcControllerGetOhlc503
>;

/**
 * @summary Get OHLC candles for a time window
 */

export function useOhlcControllerGetOhlc<
  TData = Awaited<ReturnType<typeof ohlcControllerGetOhlc>>,
  TError = ErrorType<OhlcControllerGetOhlc401 | OhlcControllerGetOhlc503>,
>(
  params: OhlcControllerGetOhlcParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof ohlcControllerGetOhlc>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getOhlcControllerGetOhlcQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns pending LP distribution batches with rewards, shares, and destinations. Header: Authorization: Bearer {APP_API_KEY}
 * @summary Get LP distribution pending batches
 */
export const distributionControllerGetPendingBatches = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<DistributionControllerGetPendingBatches200>(
    { url: `/api/v1/distribution/batches/pending`, method: "GET", signal },
    options,
  );
};

export const getDistributionControllerGetPendingBatchesQueryKey = () => {
  return [`/api/v1/distribution/batches/pending`] as const;
};

export const getDistributionControllerGetPendingBatchesQueryOptions = <
  TData = Awaited<ReturnType<typeof distributionControllerGetPendingBatches>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof distributionControllerGetPendingBatches>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getDistributionControllerGetPendingBatchesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof distributionControllerGetPendingBatches>>
  > = ({ signal }) =>
    distributionControllerGetPendingBatches(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof distributionControllerGetPendingBatches>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DistributionControllerGetPendingBatchesQueryResult = NonNullable<
  Awaited<ReturnType<typeof distributionControllerGetPendingBatches>>
>;
export type DistributionControllerGetPendingBatchesQueryError = ErrorType<void>;

/**
 * @summary Get LP distribution pending batches
 */

export function useDistributionControllerGetPendingBatches<
  TData = Awaited<ReturnType<typeof distributionControllerGetPendingBatches>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof distributionControllerGetPendingBatches>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getDistributionControllerGetPendingBatchesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Queries settled orders that are not anchored yet, builds a Merkle batch, and submits it through the configured HCS publisher.
 * @summary Run one anchor batch for settled orders
 */
export const hcsAnchorControllerRunAnchor = (
  runAnchorBatchDto: BodyType<RunAnchorBatchDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    {
      url: `/api/v1/hcs-anchor/run`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: runAnchorBatchDto,
      signal,
    },
    options,
  );
};

export const getHcsAnchorControllerRunAnchorMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof hcsAnchorControllerRunAnchor>>,
    TError,
    { data: BodyType<RunAnchorBatchDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof hcsAnchorControllerRunAnchor>>,
  TError,
  { data: BodyType<RunAnchorBatchDto> },
  TContext
> => {
  const mutationKey = ["hcsAnchorControllerRunAnchor"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof hcsAnchorControllerRunAnchor>>,
    { data: BodyType<RunAnchorBatchDto> }
  > = (props) => {
    const { data } = props ?? {};

    return hcsAnchorControllerRunAnchor(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type HcsAnchorControllerRunAnchorMutationResult = NonNullable<
  Awaited<ReturnType<typeof hcsAnchorControllerRunAnchor>>
>;
export type HcsAnchorControllerRunAnchorMutationBody =
  BodyType<RunAnchorBatchDto>;
export type HcsAnchorControllerRunAnchorMutationError = ErrorType<unknown>;

/**
 * @summary Run one anchor batch for settled orders
 */
export const useHcsAnchorControllerRunAnchor = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof hcsAnchorControllerRunAnchor>>,
    TError,
    { data: BodyType<RunAnchorBatchDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof hcsAnchorControllerRunAnchor>>,
  TError,
  { data: BodyType<RunAnchorBatchDto> },
  TContext
> => {
  const mutationOptions =
    getHcsAnchorControllerRunAnchorMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary List anchor batches
 */
export const hcsAnchorControllerGetBatches = (
  params?: HcsAnchorControllerGetBatchesParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/v1/hcs-anchor/batches`, method: "GET", params, signal },
    options,
  );
};

export const getHcsAnchorControllerGetBatchesQueryKey = (
  params?: HcsAnchorControllerGetBatchesParams,
) => {
  return [`/api/v1/hcs-anchor/batches`, ...(params ? [params] : [])] as const;
};

export const getHcsAnchorControllerGetBatchesQueryOptions = <
  TData = Awaited<ReturnType<typeof hcsAnchorControllerGetBatches>>,
  TError = ErrorType<unknown>,
>(
  params?: HcsAnchorControllerGetBatchesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof hcsAnchorControllerGetBatches>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHcsAnchorControllerGetBatchesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof hcsAnchorControllerGetBatches>>
  > = ({ signal }) =>
    hcsAnchorControllerGetBatches(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof hcsAnchorControllerGetBatches>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HcsAnchorControllerGetBatchesQueryResult = NonNullable<
  Awaited<ReturnType<typeof hcsAnchorControllerGetBatches>>
>;
export type HcsAnchorControllerGetBatchesQueryError = ErrorType<unknown>;

/**
 * @summary List anchor batches
 */

export function useHcsAnchorControllerGetBatches<
  TData = Awaited<ReturnType<typeof hcsAnchorControllerGetBatches>>,
  TError = ErrorType<unknown>,
>(
  params?: HcsAnchorControllerGetBatchesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof hcsAnchorControllerGetBatches>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHcsAnchorControllerGetBatchesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get anchor batch details
 */
export const hcsAnchorControllerGetBatch = (
  batchId: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/v1/hcs-anchor/batches/${batchId}`, method: "GET", signal },
    options,
  );
};

export const getHcsAnchorControllerGetBatchQueryKey = (batchId?: string) => {
  return [`/api/v1/hcs-anchor/batches/${batchId}`] as const;
};

export const getHcsAnchorControllerGetBatchQueryOptions = <
  TData = Awaited<ReturnType<typeof hcsAnchorControllerGetBatch>>,
  TError = ErrorType<unknown>,
>(
  batchId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof hcsAnchorControllerGetBatch>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHcsAnchorControllerGetBatchQueryKey(batchId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof hcsAnchorControllerGetBatch>>
  > = ({ signal }) =>
    hcsAnchorControllerGetBatch(batchId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!batchId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof hcsAnchorControllerGetBatch>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HcsAnchorControllerGetBatchQueryResult = NonNullable<
  Awaited<ReturnType<typeof hcsAnchorControllerGetBatch>>
>;
export type HcsAnchorControllerGetBatchQueryError = ErrorType<unknown>;

/**
 * @summary Get anchor batch details
 */

export function useHcsAnchorControllerGetBatch<
  TData = Awaited<ReturnType<typeof hcsAnchorControllerGetBatch>>,
  TError = ErrorType<unknown>,
>(
  batchId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof hcsAnchorControllerGetBatch>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHcsAnchorControllerGetBatchQueryOptions(
    batchId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Verify an anchor batch against the configured publisher
 */
export const hcsAnchorControllerVerifyBatchTopic = (
  batchId: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    {
      url: `/api/v1/hcs-anchor/batches/${batchId}/verify-topic`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getHcsAnchorControllerVerifyBatchTopicQueryKey = (
  batchId?: string,
) => {
  return [`/api/v1/hcs-anchor/batches/${batchId}/verify-topic`] as const;
};

export const getHcsAnchorControllerVerifyBatchTopicQueryOptions = <
  TData = Awaited<ReturnType<typeof hcsAnchorControllerVerifyBatchTopic>>,
  TError = ErrorType<unknown>,
>(
  batchId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof hcsAnchorControllerVerifyBatchTopic>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getHcsAnchorControllerVerifyBatchTopicQueryKey(batchId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof hcsAnchorControllerVerifyBatchTopic>>
  > = ({ signal }) =>
    hcsAnchorControllerVerifyBatchTopic(batchId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!batchId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof hcsAnchorControllerVerifyBatchTopic>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HcsAnchorControllerVerifyBatchTopicQueryResult = NonNullable<
  Awaited<ReturnType<typeof hcsAnchorControllerVerifyBatchTopic>>
>;
export type HcsAnchorControllerVerifyBatchTopicQueryError = ErrorType<unknown>;

/**
 * @summary Verify an anchor batch against the configured publisher
 */

export function useHcsAnchorControllerVerifyBatchTopic<
  TData = Awaited<ReturnType<typeof hcsAnchorControllerVerifyBatchTopic>>,
  TError = ErrorType<unknown>,
>(
  batchId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof hcsAnchorControllerVerifyBatchTopic>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHcsAnchorControllerVerifyBatchTopicQueryOptions(
    batchId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Merkle proof for an anchored order
 */
export const hcsAnchorControllerGetOrderProof = (
  orderId: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    {
      url: `/api/v1/hcs-anchor/orders/${orderId}/proof`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getHcsAnchorControllerGetOrderProofQueryKey = (
  orderId?: string,
) => {
  return [`/api/v1/hcs-anchor/orders/${orderId}/proof`] as const;
};

export const getHcsAnchorControllerGetOrderProofQueryOptions = <
  TData = Awaited<ReturnType<typeof hcsAnchorControllerGetOrderProof>>,
  TError = ErrorType<unknown>,
>(
  orderId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof hcsAnchorControllerGetOrderProof>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getHcsAnchorControllerGetOrderProofQueryKey(orderId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof hcsAnchorControllerGetOrderProof>>
  > = ({ signal }) =>
    hcsAnchorControllerGetOrderProof(orderId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orderId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof hcsAnchorControllerGetOrderProof>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HcsAnchorControllerGetOrderProofQueryResult = NonNullable<
  Awaited<ReturnType<typeof hcsAnchorControllerGetOrderProof>>
>;
export type HcsAnchorControllerGetOrderProofQueryError = ErrorType<unknown>;

/**
 * @summary Get Merkle proof for an anchored order
 */

export function useHcsAnchorControllerGetOrderProof<
  TData = Awaited<ReturnType<typeof hcsAnchorControllerGetOrderProof>>,
  TError = ErrorType<unknown>,
>(
  orderId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof hcsAnchorControllerGetOrderProof>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHcsAnchorControllerGetOrderProofQueryOptions(
    orderId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
